---

- name: Launch composer dependencies
  shell: cd {{ site_directory_version }} && [ -e "composer.json" ] && composer install -o -q || echo "No dependencies found."
  sudo: yes
  tags:
    - website

- name: Install npm dependencies
  shell: cd {{ site_directory_version }} && [ -e "package.json" ] && npm install -o || echo "No dependencies found."
  sudo: yes
  tags:
    - website

- name: Install bower dependencies
  shell: cd {{ site_directory_version }} && [ -e "bower.json" ] && bower install --allow-root ./ || echo "No dependencies found."
  sudo: yes
  tags:
    - website

- name: Execute grunt file
  shell: cd {{ site_directory_version }} && [ -e "Gruntfile.js" ] && LANG=en_US.UTF-8 grunt {{ env }} -o || echo "No grunt file found."
  sudo: yes
  tags:
    - website
