---

- name: Create directories
  file: dest={{ site_directory_root }}/.common/{{ item }} owner={{ site_user }} group={{ site_group }} mode=0775 state=directory
  with_items: current.common.dir
  when: current.common.dir is defined
  tags:
    - website

- name: Create symlink
  file: src={{ site_directory_root }}/.common/{{ item.src }} dest={{ site_directory_version }}/{{ item.dest }} owner={{ site_user }} group={{ site_group }} force=yes state=link
  with_items: current.common.symlink
  when: current.common.symlink is defined
  tags:
    - website
