---

- name: Add group
  group: name={{ site_group }} state=present
  tags:
    - website

- name: Add user
  user: name={{ site_user }} group={{ site_group }} state=present createhome=no
  tags:
    - website

- name: Add nginx host files
  template: src=../../../vhosts/{{ name }}.conf.j2 dest=/etc/nginx/conf.d/{{ name }}.conf owner=root mode=644
  notify: restart nginx
  tags:
    - website

- name: Copy ssl cert file
  copy: src=../../../ssl/{{ current.ssl.cert }} dest={{ website.directory.ssl.cert }}{{ current.ssl.cert }}
  when: current.ssl.cert is defined
  tags:
    - website

- name: Copy ssl key file
  copy: src=../../../ssl/{{ current.ssl.key }} dest={{ website.directory.ssl.key }}{{ current.ssl.key }}
  when: current.ssl.key is defined
  tags:
    - website
