---

- name: Install cronjobs
  cron: job="{{ item.prefix|default('') }}{{ site_directory_root }}/release/{{ item.job }} > {{ item.out|default('/dev/null 2>&1') }}"
        minute="{{ item.minute|default('*')}}"
        hour="{{ item.hour|default('*')}}"
        day="{{ item.day|default('*')}}"
        month="{{ item.month|default('*')}}"
        weekday="{{ item.weekday|default('*')}}"
        state="{{ item.day|default('present')}}"
        user="{{ item.day|default(user)}}"
        reboot="{{ item.day|default('no')}}"
        name="{{ name }} {{ item.job }}"
  with_items: current.cron
  when: current.cron is defined
  tags:
    - website
    - cron
