---

- name: Restart mongodb
  command: sudo service mongod restart --noauth
  tags:
    - website

- name: Add database user
  mongodb_user: 
    database="{{ current.mongodb.dbname }}"
    name="{{ current.mongodb.username }}"
    password="{{ current.mongodb.password }}"
    state=present
  when: current.mongodb
  tags:
    - website

- name: Restart mongodb
  shell: service mongod restart --auth
  tags:
    - website