---

- name: Create website directory
  file: dest={{ site_directory_root }} owner={{ site_user }} group={{ site_group }} mode=0775 state=directory
  tags:
    - website

- name: Clone repository
  git: repo={{ current.git }} dest={{ site_directory_version }} version={{ site_version }} update=yes accept_hostkey=yes
  when: current.git is defined
  tags:
    - website