---

- name: Install nginx
  apt: name=nginx-full state=present update_cache=true
  tags:
    - nginx

- name: Define new default index file
  copy: src=index.html dest=/usr/share/nginx/www/index.html
  tags:
    - nginx

- name: Update nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ item.key }}.conf
  with_dict: nginx.conf
  tags:
    - nginx