---

- include: common.yml

- name: Install webserver
  hosts: webserver
  user: vagrant
  sudo: yes

  roles:
    - nginx
    - nodejs
    - bower
    - grunt
    - ruby
    - compass
    - sails
    - { role: samba, when: "env == 'dev'" }
    - mongodb

- name: Install application
  hosts: webserver
  user: vagrant
  sudo: yes

  roles:
    - { role: website, tags: ["web"], current: "{{ jarvis['web'] }}", name: "web" }
    - { role: website, tags: ["api"], website: "{{ jarvis['api'] }}", name: "api" }