---

- include: common.yml

- name: Install web servers
  hosts: web
  sudo: yes

  roles:
    - nginx
    - nodejs
    - bower
    - grunt
    - ruby
    - compass
    - sails
    - { role: yeoman, when: "env == 'dev'" }

- name: Install database servers
  hosts: web
  sudo: yes

  roles:
    - mongodb
