---

- fail: msg="Samba should not be installed in production environnement."
  when: env != "dev"

- name: Install samba package
  apt: name=samba state=latest update_cache=true
  tags: 
    - samba

- name: Apply configuration
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf
  tags: 
    - samba
  notify: restart samba

- name: Add vagrant user
  shell: "(echo vagrant; echo vagrant) | smbpasswd -L -s -a vagrant"
  tags: 
    - samba
  notify: restart samba

- name: Setup user right
  file: path={{ web_directory }} state=directory owner=vagrant group=vagrant recurse=yes mode=0755
  tags: 
    - samba
  notify: restart samba